import time
import traceback
import sys

# --- CHOOSE YOUR MODE ---
# True: Run the rule-based bot to gather "expert" data into the database.
# False: Run the new Deep Learning agent (once it's trained).
DATA_COLLECTION_MODE = True

# If not in data collection mode, specify the trained model to use.
# This file would be generated by your RL training script.
RL_MODEL_PATH = "ironclad_brain_rl_episode_1000.pth"

from rs.ai.deep_learning.rl_agent import RLAgent
from rs.helper.seed import make_random_seed
from rs.api.client import Client
from rs.machine.game import Game
from rs.helper.logger import log, init_log, log_new_run_sequence
from rs.ai.mir_ironclad.ironclad_will import IRON_WILL


# --- SAFE IMPORT (No Prints allowed) ---
try:
    from logger import STSLogger
    DB_AVAILABLE = True
except Exception as e:
    log(f"WARNING: Database logger disabled. {e}")
    DB_AVAILABLE = False

run_seeds = []
run_amount = 100 # Let's collect a good amount of data!

if DATA_COLLECTION_MODE:
    strategy = IRON_WILL
else:
    strategy = RLAgent(model_path=RL_MODEL_PATH)

if __name__ == "__main__":
    init_log()
    log("Starting up")
    log_new_run_sequence()
    
    try:
        client = Client()
        game = Game(client, strategy)
        
        # Attach logger if it successfully imported
        if DB_AVAILABLE:
            game.logger = STSLogger(strategy_name=strategy.name)

        if run_seeds:
            for seed in run_seeds:
                game.start(seed)
                game.run()
                time.sleep(1)
        else:
            for i in range(run_amount):
                game.start(make_random_seed())
                game.run()
                time.sleep(1)

    except Exception as e:
        log("Exception! " + str(e))
        log(traceback.format_exc())